### ISSUE TITLE
Provision this extension on a new box fails

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/nodejs#37]
A fresh Chassis install with just this extension doesn't install node as expected:
```
 default: Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install clang-3.4' returned 100: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: Package clang-3.4 is not available, but is referred to by another package.
    default: This may mean that the package is missing, has been obsoleted, or
    default: is only available from another source
    default: However the following packages replace it:
    default:   clang
    default: 
    default: E: Package 'clang-3.4' has no installation candidate
    default: Error: /Stage[main]/Nodejs/Package[clang-3.4]/ensure: change from 'purged' to 'latest' failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install clang-3.4' returned 100: Reading package lists...
    default: Building dependency tree...
    default: Reading state information...
    default: Package clang-3.4 is not available, but is referred to by another package.
    default: This may mean that the package is missing, has been obsoleted, or
    default: is only available from another source
    default: However the following packages replace it:
    default:   clang
    default: 
    default: E: Package 'clang-3.4' has no installation candidate

```
